//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstoqueMangas.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EstoqueMangas.Domain.Resources.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} é inválido. Favor inserir um número maior que {1}..
        /// </summary>
        internal static string CAMPO_X0_INVALIDO_FAVOR_INSERIR_NUMERO_MAIOR_QUE_X1 {
            get {
                return ResourceManager.GetString("CAMPO_X0_INVALIDO_FAVOR_INSERIR_NUMERO_MAIOR_QUE_X1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha ao realizar a operação..
        /// </summary>
        internal static string FALHA_AO_REALIZAR_A_OPERACAO {
            get {
                return ResourceManager.GetString("FALHA_AO_REALIZAR_A_OPERACAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha deve ter entre {0} e {1} caracteres.
        /// </summary>
        internal static string O_CAMPO_X0_DEVE_TER_ENTRE_X1_E_X2_CARACTERES {
            get {
                return ResourceManager.GetString("O_CAMPO_X0_DEVE_TER_ENTRE_X1_E_X2_CARACTERES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} é uma informação obrigatória..
        /// </summary>
        internal static string O_CAMPO_X0_E_INFORMACAO_OBRIGATORIA {
            get {
                return ResourceManager.GetString("O_CAMPO_X0_E_INFORMACAO_OBRIGATORIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo {0} é inválido..
        /// </summary>
        internal static string O_CAMPO_X0_E_INVALIDO {
            get {
                return ResourceManager.GetString("O_CAMPO_X0_E_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Operação realizada com sucesso..
        /// </summary>
        internal static string OPERACAO_REALIZADA_COM_SUCESSO {
            get {
                return ResourceManager.GetString("OPERACAO_REALIZADA_COM_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} alterada com sucesso..
        /// </summary>
        internal static string X0_ALTERADA_COM_SUCESSO {
            get {
                return ResourceManager.GetString("X0_ALTERADA_COM_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} alterado com sucesso..
        /// </summary>
        internal static string X0_ALTERADO_COM_SUCESSO {
            get {
                return ResourceManager.GetString("X0_ALTERADO_COM_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} cadastrada com sucesso..
        /// </summary>
        internal static string X0_CADASTRADA_COM_SUCESSO {
            get {
                return ResourceManager.GetString("X0_CADASTRADA_COM_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} cadastrado com sucesso..
        /// </summary>
        internal static string X0_CADASTRADO_COM_SUCESSO {
            get {
                return ResourceManager.GetString("X0_CADASTRADO_COM_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} {1} excluída com sucesso..
        /// </summary>
        internal static string X0_EXCLUIDA_COM_SUCESSO {
            get {
                return ResourceManager.GetString("X0_EXCLUIDA_COM_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} excluído com sucesso..
        /// </summary>
        internal static string X0_EXCLUIDO_COM_SUCESSO {
            get {
                return ResourceManager.GetString("X0_EXCLUIDO_COM_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0) já cadastrada..
        /// </summary>
        internal static string X0_JA_CADASTRADA {
            get {
                return ResourceManager.GetString("X0_JA_CADASTRADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} já cadastrado..
        /// </summary>
        internal static string X0_JA_CADASTRADO {
            get {
                return ResourceManager.GetString("X0_JA_CADASTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} não encontrada..
        /// </summary>
        internal static string X0_NAO_ENCONTRADA {
            get {
                return ResourceManager.GetString("X0_NAO_ENCONTRADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} não encontrado..
        /// </summary>
        internal static string X0_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("X0_NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} {1} alterada com sucesso..
        /// </summary>
        internal static string X0_X1_ALTERADA_COM_SUCESSO {
            get {
                return ResourceManager.GetString("X0_X1_ALTERADA_COM_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} {1} alterado com sucesso..
        /// </summary>
        internal static string X0_X1_ALTERADO_COM_SUCESSO {
            get {
                return ResourceManager.GetString("X0_X1_ALTERADO_COM_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} {1} cadastrada com sucesso..
        /// </summary>
        internal static string X0_X1_CADASTRADA_COM_SUCESSO {
            get {
                return ResourceManager.GetString("X0_X1_CADASTRADA_COM_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} {1} cadastrado com sucesso..
        /// </summary>
        internal static string X0_X1_CADASTRADO_COM_SUCESSO {
            get {
                return ResourceManager.GetString("X0_X1_CADASTRADO_COM_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} {1} excluída com sucesso..
        /// </summary>
        internal static string X0_X1_EXCLUIDA_COM_SUCESSO {
            get {
                return ResourceManager.GetString("X0_X1_EXCLUIDA_COM_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} {1} excluído com sucesso..
        /// </summary>
        internal static string X0_X1_EXCLUIDO_COM_SUCESSO {
            get {
                return ResourceManager.GetString("X0_X1_EXCLUIDO_COM_SUCESSO", resourceCulture);
            }
        }
    }
}
