//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstoqueMangas.Domain.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Message {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("EstoqueMangas.Domain.Resources.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string CAMPO_X0_INVALIDO_FAVOR_INSERIR_NUMERO_MAIOR_QUE_X1 {
            get {
                return ResourceManager.GetString("CAMPO_X0_INVALIDO_FAVOR_INSERIR_NUMERO_MAIOR_QUE_X1", resourceCulture);
            }
        }
        
        internal static string ERRO_INTERNO {
            get {
                return ResourceManager.GetString("ERRO_INTERNO", resourceCulture);
            }
        }
        
        internal static string FALHA_AO_REALIZAR_A_OPERACAO {
            get {
                return ResourceManager.GetString("FALHA_AO_REALIZAR_A_OPERACAO", resourceCulture);
            }
        }
        
        internal static string OPERACAO_REALIZADA_COM_SUCESSO {
            get {
                return ResourceManager.GetString("OPERACAO_REALIZADA_COM_SUCESSO", resourceCulture);
            }
        }
        
        internal static string O_CAMPO_X0_DEVE_TER_ENTRE_X1_E_X2_CARACTERES {
            get {
                return ResourceManager.GetString("O_CAMPO_X0_DEVE_TER_ENTRE_X1_E_X2_CARACTERES", resourceCulture);
            }
        }
        
        internal static string O_CAMPO_X0_E_INFORMACAO_OBRIGATORIA {
            get {
                return ResourceManager.GetString("O_CAMPO_X0_E_INFORMACAO_OBRIGATORIA", resourceCulture);
            }
        }
        
        internal static string O_CAMPO_X0_E_INVALIDO {
            get {
                return ResourceManager.GetString("O_CAMPO_X0_E_INVALIDO", resourceCulture);
            }
        }
        
        internal static string X0_ALTERADA_COM_SUCESSO {
            get {
                return ResourceManager.GetString("X0_ALTERADA_COM_SUCESSO", resourceCulture);
            }
        }
        
        internal static string X0_ALTERADO_COM_SUCESSO {
            get {
                return ResourceManager.GetString("X0_ALTERADO_COM_SUCESSO", resourceCulture);
            }
        }
        
        internal static string X0_CADASTRADA_COM_SUCESSO {
            get {
                return ResourceManager.GetString("X0_CADASTRADA_COM_SUCESSO", resourceCulture);
            }
        }
        
        internal static string X0_CADASTRADO_COM_SUCESSO {
            get {
                return ResourceManager.GetString("X0_CADASTRADO_COM_SUCESSO", resourceCulture);
            }
        }
        
        internal static string X0_EXCLUIDA_COM_SUCESSO {
            get {
                return ResourceManager.GetString("X0_EXCLUIDA_COM_SUCESSO", resourceCulture);
            }
        }
        
        internal static string X0_EXCLUIDO_COM_SUCESSO {
            get {
                return ResourceManager.GetString("X0_EXCLUIDO_COM_SUCESSO", resourceCulture);
            }
        }
        
        internal static string X0_JA_CADASTRADA {
            get {
                return ResourceManager.GetString("X0_JA_CADASTRADA", resourceCulture);
            }
        }
        
        internal static string X0_JA_CADASTRADO {
            get {
                return ResourceManager.GetString("X0_JA_CADASTRADO", resourceCulture);
            }
        }
        
        internal static string X0_NAO_ENCONTRADA {
            get {
                return ResourceManager.GetString("X0_NAO_ENCONTRADA", resourceCulture);
            }
        }
        
        internal static string X0_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("X0_NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        internal static string X0_X1_ALTERADA_COM_SUCESSO {
            get {
                return ResourceManager.GetString("X0_X1_ALTERADA_COM_SUCESSO", resourceCulture);
            }
        }
        
        internal static string X0_X1_ALTERADO_COM_SUCESSO {
            get {
                return ResourceManager.GetString("X0_X1_ALTERADO_COM_SUCESSO", resourceCulture);
            }
        }
        
        internal static string X0_X1_CADASTRADA_COM_SUCESSO {
            get {
                return ResourceManager.GetString("X0_X1_CADASTRADA_COM_SUCESSO", resourceCulture);
            }
        }
        
        internal static string X0_X1_CADASTRADO_COM_SUCESSO {
            get {
                return ResourceManager.GetString("X0_X1_CADASTRADO_COM_SUCESSO", resourceCulture);
            }
        }
        
        internal static string X0_X1_EXCLUIDA_COM_SUCESSO {
            get {
                return ResourceManager.GetString("X0_X1_EXCLUIDA_COM_SUCESSO", resourceCulture);
            }
        }
        
        internal static string X0_X1_EXCLUIDO_COM_SUCESSO {
            get {
                return ResourceManager.GetString("X0_X1_EXCLUIDO_COM_SUCESSO", resourceCulture);
            }
        }
    }
}
